# Generated by Django 4.2.14 on 2024-07-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='farmermodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('livestock', models.CharField(max_length=50)),
                ('crop', models.CharField(max_length=50)),
                ('profit_or_loss', models.IntegerField()),
            ],
        ),
    ]
